### ISSUE TITLE
Better rewrite of Tracebacks

### ISSUE THREAD

**Issue by alfredodeza** [alfredodeza/konira#6]
Konira already rewrites Tracebacks, but it doesn't "translate" the methods or classes where the tracebacks end.

So you get to see things like this:

```
Traceback (most recent call last):
  File "/private/tmp/vkonira/konira/konira/tests/case_exc.py", line 18, in it_asks_if_you_are_using_pdb
    assert self.dont_read.msg == messages
NameError: global name 'messages' is not defined
```

When it would be awesome to see them like this:

```
Traceback (most recent call last):
  File "/private/tmp/vkonira/konira/konira/tests/case_exc.py", line 18, in it "asks if you are using pdb"
    assert self.dont_read.msg == messages
NameError: global name 'messages' is not defined
```

**Comment by alfredodeza** [comment]
Completed for version 0.2.0
